import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

import { fontNotoSansSC } from "@/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import DeNavBar from "@/components/ui/nav/MotionNav/DeNavBar";
import Variants from "@/components/ui/nav/MotionNav/Variants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          fontNotoSansSC.className,

          "antialiased",
        )}
      >
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          <Variants />
          <DeNavBar />
          <main className={"w-full mx-auto h-full"}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
